### ISSUE TITLE
Có nên sửa lại tên file classification.py

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/classification#15]
@JackNhat Nên để tên file là `classification.py` hay `predict.py` nhỉ?

Hiện tại anh thích `predict.py` hơn, khi đó thư mục gốc sẽ có `train.py`, `predict.py`

**Comment by JackNhat** [comment]
em thấy để `classification.py` hay `predict.py` cũng đều hợp lý cả, tạm thời chưa cần đổi :)))

**Comment by rain1024** [comment]
ok, vậy thì giữ nguyên :D
