### ISSUE TITLE
Sửa lại phần readme

### ISSUE THREAD

**Issue by khanhmd58** [undertheseanlp/classification#17]
em nghĩ nên sửa lại phần readme cho những người beginner dễ hình dung và training data

**Comment by rain1024** [comment]
cụ thể là thế nào @khanhmd58 ?

**Comment by rain1024** [comment]
@JackNhat nghĩ thế nào về vụ này. tại vì thằng @khanhmd58 không nói rõ nên cũng khó thảo luận

**Comment by khanhmd58** [comment]
cụ thể là:
Huấn luyện mô hình
Chuẩn bị tập dữ liệu mới

tập dữ liệu của bạn được quy chuẩn như tập dữ liệu trong thư mục data/raw 

Chuyển đổi tập dữ liệu của bạn thành file excel
