### ISSUE TITLE
Review Sprint 10/2018

### ISSUE THREAD

**Issue by khanhmd58** [undertheseanlp/classification#27]
- Phần README cần thay vị trí phần sử dụng mô hình đã huấn luyện sẵn xuống phía dưới sau khi training model vì model vẫn chưa được build khi người dùng clone code về
- Phần Reproduce chuẩn không cần thay đổi gì
- Phần Report kết quả báo cáo không sai lệch là mấy.

* Bổ sung file quá nặng không nên lưu ở github

**Comment by rain1024** [comment]
cảm ơn @khanhmd58 nhé

**Comment by rain1024** [comment]
anh đã xử lý vụ file data nặng rồi. @JackNhat  xử lý việc thêm pre-trained model nhé

**Comment by rain1024** [comment]
@JackNhat , vấn đề thêm mô hình là vấn đề đầu tiên mà @khanhmd58 nêu ra đấy

em chưa add mô hình mặc định vào, nên khi người dùng clone code về thì phải train mô hình mới predict

**Comment by JackNhat** [comment]
@rain1024 bởi vì những file .bin ở thư mục model thường khá nặng nên em ignore nó đi. Khi clone code về thì k có những file này nên phải train lại mô hình. Giải pháp đưa ra là bỏ ignore các file .bin này đi

**Comment by rain1024** [comment]
Em ignore là .bin là chuẩn rồi. Anh nghĩ em không nên bỏ ignore. Mà nên dùng `git add -f ` để thêm chỉ DUY NHẤT một mô hình tốt nhất thôi.

**Comment by rain1024** [comment]
models của fasttext à? sao lại lớn thế nhỉ?

**Comment by JackNhat** [comment]
Mô hình hiện tại đang dùng SVM + CountVectorizer, có thể nén nhỏ mô hình lại với param `compress` của joblib. Tuy nhiên nếu mô hình nén càng nhỏ thì khi load model càng mất nhiều thời gian

**Comment by rain1024** [comment]
@JackNhat em dùng compress kết quả thế nào?

**Comment by JackNhat** [comment]
Em dùng `compress=2` nén model từ 223, 4 MB xuống còn 13, 9 MB. Thời gian load model nếu chưa nén là 12.75s và 15.12s với model đã nén.

**Comment by rain1024** [comment]
Thống kê số liệu rất đầy đủ +1 like

Load model mất tận 12.75s hả. Sao lâu thế?

**Comment by JackNhat** [comment]
là em sai ạ, `ms` chứ không phải `s`, em đã sửa lại

**Comment by JackNhat** [comment]
vâng. Khi không dùng `compress` thì model nặng (223,4 MB), thời gian load model vào RAM lâu, còn khi dùng `compress` thì mất thời gian để giải nén. Thời gian để predict thì nhanh 0.002s

**Comment by rain1024** [comment]
Thế thì cho model 13.9 MB vào default đi. Rồi gửi merge request nhé

**Comment by JackNhat** [comment]
em đã gửi pull request rồi đấy ạ
