### ISSUE TITLE
Dữ liệu train chưa đủ tại classification/data/corpus/train.xlxs

### ISSUE THREAD

**Issue by nvlong198** [undertheseanlp/classification#30]
chỉ có 12076/14375

**Comment by rain1024** [comment]
Cảm ơn @nvlong198. Nhóm mình cũng đang fix issue này

**Comment by rain1024** [comment]
Hi @nvlong198,

Hiện tại, dữ liệu đã được cập nhật, gồm 33759 văn bản (training) và 50373 văn bản (testing) cho 10 topic.

@nvlong198 review xem có ổn không nhé.

thanks

**Comment by nvlong198** [comment]
@rain1024 dữ liệu 10 topic mình thấy đủ, nhưng còn của bộ 27 trước ko update nên đây nữa sao b ? :D

**Comment by rain1024** [comment]
Đúng rồi @nvlong198, vì bộ đấy có nhiều topic hơi thừa `hackers and viruses` và `new computer products` và `computer entertainment` cùng thuộc chủ đề `computer`

![image](https://user-images.githubusercontent.com/1780281/48237729-8c4d3780-e3fa-11e8-9a44-a14574b5b0d1.png)

Trong khi đó bộ 10 topic thì nhiều dữ liệu hơn, các topic cũng tổ chức hợp lý hơn

![image](https://user-images.githubusercontent.com/1780281/48237774-d1716980-e3fa-11e8-8665-20b739758fd1.png)

Bộ 10 topic cũng có nhiều dữ liệu cho mỗi nhãn, nên nhóm mình quyết định sẽ dùng bộ 10 topic. 

Rất mong @nvlong198 có thể contribute phần 27 topic cho dự án này :D
