### ISSUE TITLE
E hỏi chút về lỗi khi cài đặt

### ISSUE THREAD

**Issue by Nlight9x** [undertheseanlp/classification#50]
Hi anh e là newbie. Em đang cài đặt thử lib classification, khi chạy thử thì gặp lỗi như sau.
```
Traceback (most recent call last):
  File "classification.py", line 6, in <module>
    from models import classifier
ModuleNotFoundError: No module named 'models'
```
Trước khi báo lỗi này thì có hiện lỗi  thiếu lib "ftfy". E đã install lại trong lib tương tự ở trong file requirement thì thấy ko báo lỗi nữa. E đoán lỗi trên cũng tương tự, nên đã install lần lượt lại. Nhưng vẫn chưa fix được. A xem giúp e xem là lỗi gì với ạ, thank anh.

**Comment by Nlight9x** [comment]
Trong thư mục classification luôn ạ

**Comment by rain1024** [comment]
> Trong thư mục classification luôn ạ

Em chạy script nào? Em dùng hệ điều hành gì?

**Comment by Nlight9x** [comment]
E chạy script thử phân loại classification.py thử 1 đoạn văn bản (giống trong doc mô tả) đó ạ. HĐH: MacOS ạ.

**Comment by Nlight9x** [comment]
cụ thể là đoạn này ạ
`$ python classification.py "Trong phần lớn thời gian sáng nay, thầy trò HLV Park Hang Seo có cuộc họp nội bộ tại khách sạn. Tại cuộc họp này, nội dung quan trọng nhất chính là xem băng ghi hình một số trận đấu gần nhất của đội chủ nhà, giúp đội tuyển Việt Nam đưa ra những phương án đối phó trong trận ra quân tại AFF Cup 2018 sắp tới."`

lỗi báo ở line 6 trong file "classification.py" đoạn `from models import classifier` ạ. :(
Thank anh.

**Comment by rain1024** [comment]
@Nlight9x Em đã chạy được chương trình chưa?

**Comment by Nlight9x** [comment]
Thank anh + team. Em đã tải toàn bộ dữ liệu VNTC về r. Chỉnh sửa lại 1 chút code trong folder fasttext đã chạy đc r ạ. Độ chính xác cũng gần gần giống như mô tả. 
Có điều e hơi thắc mắc một chút là nếu em thử mỗi label training chỉ lấy tầm 20 dòng trong file training thì kết quả lúc classify lúc nào cũng chỉ ra một label duy nhất. Kể cả e có copy text trong dữ liệu dùng training vẫn vậy. Em nghĩ là dù ít dữ liệu train thì nó cũng phải nhảy ra các label khác chứ ạ. :D

**Comment by rain1024** [comment]
Anh nghĩ vụ chỉ ra một label là do thuật toán của fasttext thôi. Dữ liệu 20 dòng trên một label là quá ít để nó phân loại
