### ISSUE TITLE
Cho em hỏi phần mềm này có hỗ trợ phân loại đa nhãn không ạ

### ISSUE THREAD

**Issue by nhannt315** [undertheseanlp/classification#52]

**Comment by rain1024** [comment]
Hiện tại thì repo này chưa hỗ trợ phân loại đa nhãn em nhé

**Comment by rain1024** [comment]
@nhannt315 : Trong phiên bản sắp tới, phần mềm sẽ hỗ trợ đa nhãn nhé ;)
