### ISSUE TITLE
Chuyển đổi dữ liệu sang định dạng fasttext 

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/classification#53]
Chuyển đổi định dạng dữ liệu sang định dạng được sử dụng bởi fasttext

**Comment by TQuy** [comment]
I'm sorry but which one in the list uses FastText word-embedding?
TfidfVectorizer(ngram_range=(1, 2), max_df=0.5) | 92.8
CountVectorizer(ngram_range=(1, 3), max_df=0.7) | 89.3
TfidfVectorizer(max_df=0.8) | 89.0
CountVectorizer(ngram_range=(1, 3) | 88.9
TfidfVectorizer(ngram_range=(1, 3)) | 86.8
CountVectorizer(max_df=0.7) | 85.5

**Comment by rain1024** [comment]
I think you may be misunderstand this issue. It doesn't mean use fasttext word embedding, but means convert dataset to fasttext format, which described [here](https://fasttext.cc/docs/en/supervised-tutorial.html#getting-and-preparing-the-data)

**Comment by rain1024** [comment]
Issue đã được xử lý từ phiên bản langaugeflow v1.1.13
