### ISSUE TITLE
Xảy ra lỗi khi underthesea download tc_general

### ISSUE THREAD

**Issue by quynhvan** [undertheseanlp/classification#66]
khi em chạy lệnh underthesea download tc_general thì xảy ra lỗi như vậy:
 OSError: [Winerror 123] the filename, direction name, or volume label syntax is incorrect: 'C:\\Users\\Van\\.underthesea\\models\\tc_svm_vntc_20190607.zip?dl=1'

Em vào .underthesea\\models thì không thấy có tc_svm_vntc_20190607.zip

**Comment by rain1024** [comment]
Em thử chạy trên ubuntu xem, trong Windows anh nghĩ nó không nhận thực mục `.underthesea\models` đâu

**Comment by quynhvan** [comment]
Dạ vâng, em đang cài ubuntu rồi ạ.
